# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    manipulator_2_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    manipulator_2_gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

manipulator_2_arm_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
manipulator_2_gripper_controller:
  ros__parameters:
    joints:
      - finger_joint1
      - finger_joint2