sensors: ["default_sensor", "other_sensor"]
# default_sensor:
#     sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /intel_realsense_r200_depth/points
#     max_range: 5.0
#     point_subsample: 1
#     padding_offset: 0.1
#     padding_scale: 1.0
#     max_update_rate: 1.0
#     filtered_cloud_topic: filtered_cloud
# other_sensor:
#     sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
